// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SantaFeWaterSystem.Data;

#nullable disable

namespace SantaFeWaterSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SantaFeWaterSystem.Models.AdminAccessSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LoginViewToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AdminAccessSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoginViewToken = "wako-kabalo-ganiiiii"
                        });
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.AdminResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AdminResetTokens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = "Monday",
                            Token = "TokenMon"
                        },
                        new
                        {
                            Id = 2,
                            Day = "Tuesday",
                            Token = "TokenTue"
                        },
                        new
                        {
                            Id = 3,
                            Day = "Wednesday",
                            Token = "TokenWed"
                        },
                        new
                        {
                            Id = 4,
                            Day = "Thursday",
                            Token = "TokenThu"
                        },
                        new
                        {
                            Id = 5,
                            Day = "Friday",
                            Token = "TokenFri"
                        },
                        new
                        {
                            Id = 6,
                            Day = "Saturday",
                            Token = "TokenSat"
                        },
                        new
                        {
                            Id = 7,
                            Day = "Sunday",
                            Token = "TokenSun"
                        });
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Announcement", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.AuditTrailArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditTrailArchives");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Backup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BackupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.BackupLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BackupLogs");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.BillNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BillingId");

                    b.HasIndex("ConsumerId");

                    b.ToTable("BillNotifications");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AdditionalFees")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("date");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CubicMeterUsed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Penalty")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PresentReading")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PreviousReading")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Consumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDisconnected")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MeterAddress")
                        .HasColumnType("text");

                    b.Property<string>("MeterNo")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Consumers");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FacebookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IntroText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WaterMeterHeading")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WaterMeterInstructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Disconnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BillingId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateDisconnected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReconnected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReconnected")
                        .HasColumnType("boolean");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BillingId");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Disconnections");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.EmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Feedback", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AnnouncementId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reply")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.FeedbackComment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CommentedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("FeedbackId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedbackComments");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.FeedbackLike", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("FeedbackId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LikedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedbackLikes");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Help", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("RoleAccess")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Helps");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.HomePageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Card1Icon")
                        .HasColumnType("text");

                    b.Property<string>("Card1Text")
                        .HasColumnType("text");

                    b.Property<string>("Card1Title")
                        .HasColumnType("text");

                    b.Property<string>("Card2Icon")
                        .HasColumnType("text");

                    b.Property<string>("Card2Text")
                        .HasColumnType("text");

                    b.Property<string>("Card2Title")
                        .HasColumnType("text");

                    b.Property<string>("Card3Icon")
                        .HasColumnType("text");

                    b.Property<string>("Card3Text")
                        .HasColumnType("text");

                    b.Property<string>("Card3Title")
                        .HasColumnType("text");

                    b.Property<string>("Card4Icon")
                        .HasColumnType("text");

                    b.Property<string>("Card4Text")
                        .HasColumnType("text");

                    b.Property<string>("Card4Title")
                        .HasColumnType("text");

                    b.Property<string>("Card5Icon")
                        .HasColumnType("text");

                    b.Property<string>("Card5Text")
                        .HasColumnType("text");

                    b.Property<string>("Card5Title")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HomePageContents");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.LockoutPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LockoutMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxFailedAccessAttempts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LockoutPolicies");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SendToAll")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordHistories");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.PasswordPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxPasswordAgeDays")
                        .HasColumnType("integer");

                    b.Property<int>("MinPasswordAgeDays")
                        .HasColumnType("integer");

                    b.Property<int>("MinPasswordLength")
                        .HasColumnType("integer");

                    b.Property<int>("PasswordHistoryCount")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireComplexity")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PasswordPolicies");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillingId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedBy")
                        .HasColumnType("text");

                    b.Property<string>("ReceiptPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BillingId");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Access to user management",
                            Name = "ManageUsers"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Access to consumer management",
                            Name = "ManageConsumers"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Access to billing management",
                            Name = "ManageBilling"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Access to payment management",
                            Name = "ManagePayments"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Access to disconnection management",
                            Name = "ManageDisconnections"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Access to reports",
                            Name = "ViewReports"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Access to notifications management",
                            Name = "ManageNotifications"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Access to support management",
                            Name = "ManageSupport"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Access to feedback management",
                            Name = "ManageFeedback"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Permission to register new admins",
                            Name = "RegisterAdmin"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Permission to register new users",
                            Name = "RegisterUser"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Permission to manage QR codes",
                            Name = "ManageQRCodes"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Permission to manage rates",
                            Name = "ManageRate"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Permission to edit user details",
                            Name = "EditUser"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Permission to reset user password",
                            Name = "ResetPassword"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Permission to delete a user",
                            Name = "DeleteUser"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Permission to reset two-factor authentication",
                            Name = "Reset2FA"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Permission to lock a user account",
                            Name = "LockUser"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Permission to unlock a user account",
                            Name = "UnlockUser"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Permission to view consumer details",
                            Name = "ViewConsumer"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Permission to edit consumer",
                            Name = "EditConsumer"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Permission to delete consumer",
                            Name = "DeleteConsumer"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Permission to view billing records",
                            Name = "ViewBilling"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Permission to edit billing records",
                            Name = "EditBilling"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Permission to delete billing records",
                            Name = "DeleteBilling"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Permission to send billing notifications",
                            Name = "NotifyBilling"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Permission to view penalty history logs",
                            Name = "ViewPenaltyLog"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Permission to view payment records",
                            Name = "ViewPayment"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Permission to edit payment records",
                            Name = "EditPayment"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Permission to delete payment records",
                            Name = "DeletePayment"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Permission to verify payment records",
                            Name = "VerifyPayment"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Permission to manage privacy policies",
                            Name = "ManagePrivacyPolicy"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Permission to manage contact information",
                            Name = "ManageContact"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Permission to manage homepage content (create, edit, delete)",
                            Name = "ManageHome"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Permission to manage system name and branding",
                            Name = "ManageSystemName"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Permission to manage community posts, announcements, and feedback",
                            Name = "ManageCommunity"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Permission to manage system backups",
                            Name = "BackupManagement"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Permission to access and modify general system settings",
                            Name = "GeneralSettings"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Permission to view and respond to user inquiries",
                            Name = "ManageInquiries"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Permission to view system audit logs",
                            Name = "ViewAuditLogs"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Permission to view SMS communication logs",
                            Name = "ViewSmsLogs"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Permission to view email communication logs",
                            Name = "ViewEmailLogs"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Can manage account policies",
                            Name = "ManageAccountPolicy"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Can manage password policies",
                            Name = "ManagePasswordPolicy"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Can manage lockout policies",
                            Name = "ManageLockoutPolicy"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Permission to manage email settings and SMTP configuration",
                            Name = "ManageEmailSettings"
                        });
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.PrivacyPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("PrivacyPolicies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is the default privacy policy.",
                            CreatedAt = new DateTime(2025, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Default Privacy Policy",
                            Version = 1
                        });
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.PrivacyPolicySection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PrivacyPolicyId")
                        .HasColumnType("integer");

                    b.Property<string>("SectionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrivacyPolicyId");

                    b.ToTable("PrivacyPolicySections");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.PublicInquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsAgreed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PublicInquiries");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RatePerCubicMeter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.RateBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxCubic")
                        .HasColumnType("integer");

                    b.Property<int?>("MinCubic")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("RatePerCubicMeter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RateBrackets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = 0,
                            BaseAmount = 130m,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxCubic = 10,
                            MinCubic = 0,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 0m
                        },
                        new
                        {
                            Id = 2,
                            AccountType = 0,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxCubic = 20,
                            MinCubic = 11,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 15m
                        },
                        new
                        {
                            Id = 3,
                            AccountType = 0,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxCubic = 30,
                            MinCubic = 21,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 17m
                        },
                        new
                        {
                            Id = 4,
                            AccountType = 0,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinCubic = 31,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 19m
                        },
                        new
                        {
                            Id = 5,
                            AccountType = 1,
                            BaseAmount = 165m,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxCubic = 10,
                            MinCubic = 0,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 0m
                        },
                        new
                        {
                            Id = 6,
                            AccountType = 1,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxCubic = 20,
                            MinCubic = 11,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 20.5m
                        },
                        new
                        {
                            Id = 7,
                            AccountType = 1,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxCubic = 30,
                            MinCubic = 21,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 24.5m
                        },
                        new
                        {
                            Id = 8,
                            AccountType = 1,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinCubic = 31,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 29.5m
                        },
                        new
                        {
                            Id = 9,
                            AccountType = 2,
                            BaseAmount = 0m,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxCubic = 5,
                            MinCubic = 0,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 0m
                        },
                        new
                        {
                            Id = 10,
                            AccountType = 2,
                            BaseAmount = 130m,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxCubic = 15,
                            MinCubic = 6,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 0m
                        },
                        new
                        {
                            Id = 11,
                            AccountType = 2,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxCubic = 25,
                            MinCubic = 16,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 15m
                        },
                        new
                        {
                            Id = 12,
                            AccountType = 2,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxCubic = 35,
                            MinCubic = 26,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 17m
                        },
                        new
                        {
                            Id = 13,
                            AccountType = 2,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinCubic = 36,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 19m
                        },
                        new
                        {
                            Id = 14,
                            AccountType = 4,
                            BaseAmount = 0m,
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinCubic = 0,
                            PenaltyAmount = 0m,
                            RatePerCubicMeter = 0m
                        });
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.SmsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("SmsLogs");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.StaffPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffPermissions");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Support", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReplySeen")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SupportFeedbackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SupportFeedbackEmoji")
                        .HasColumnType("text");

                    b.Property<string>("SupportFeedbackNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Supports");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.SystemBranding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconClass")
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SystemBrandings");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.UserPrivacyAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AgreedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("PrivacyPolicyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrivacyPolicyId");

                    b.HasIndex("ConsumerId", "PolicyVersion")
                        .IsUnique();

                    b.ToTable("UserPrivacyAgreements");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.UserPushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("P256DH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPushSubscriptions");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.VisitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VisitDateLocal")
                        .HasColumnType("date");

                    b.Property<DateTime>("VisitedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("VisitDateLocal", "IpAddress")
                        .IsUnique();

                    b.ToTable("VisitorLogs");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Announcement", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.BillNotification", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Billing", "Billing")
                        .WithMany()
                        .HasForeignKey("BillingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantaFeWaterSystem.Models.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Billing");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Billing", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Consumer", "Consumer")
                        .WithMany("Billings")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Consumer", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.User", "User")
                        .WithOne("Consumer")
                        .HasForeignKey("SantaFeWaterSystem.Models.Consumer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Disconnection", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Billing", "Billing")
                        .WithMany("Disconnections")
                        .HasForeignKey("BillingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SantaFeWaterSystem.Models.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billing");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.EmailLog", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Consumer", "Consumer")
                        .WithMany("EmailLogs")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Feedback", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Announcement", "Announcement")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AnnouncementId");

                    b.HasOne("SantaFeWaterSystem.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Announcement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.FeedbackComment", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Feedback", "Feedback")
                        .WithMany("Comments")
                        .HasForeignKey("FeedbackId");

                    b.HasOne("SantaFeWaterSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.FeedbackLike", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Feedback", "Feedback")
                        .WithMany("FeedbackLikes")
                        .HasForeignKey("FeedbackId");

                    b.HasOne("SantaFeWaterSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Notification", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Consumer", "Consumer")
                        .WithMany("Notifications")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.PasswordHistory", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Payment", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Billing", "Billing")
                        .WithMany()
                        .HasForeignKey("BillingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantaFeWaterSystem.Models.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Billing");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.PrivacyPolicySection", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.PrivacyPolicy", "PrivacyPolicy")
                        .WithMany("Sections")
                        .HasForeignKey("PrivacyPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivacyPolicy");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.SmsLog", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.StaffPermission", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantaFeWaterSystem.Models.User", "Staff")
                        .WithMany("StaffPermissions")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Support", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.UserPrivacyAgreement", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantaFeWaterSystem.Models.PrivacyPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PrivacyPolicyId");

                    b.Navigation("Consumer");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.UserPushSubscription", b =>
                {
                    b.HasOne("SantaFeWaterSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Announcement", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Billing", b =>
                {
                    b.Navigation("Disconnections");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Consumer", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("EmailLogs");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.Feedback", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FeedbackLikes");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.PrivacyPolicy", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SantaFeWaterSystem.Models.User", b =>
                {
                    b.Navigation("Consumer");

                    b.Navigation("Feedbacks");

                    b.Navigation("StaffPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
